# Generated by Django 2.0.7 on 2018-07-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.IntegerField(default=0)),
                ('scene', models.IntegerField(default=0)),
                ('lineno', models.IntegerField(default=0)),
                ('speaker', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
    ]
