# Generated by Django 2.0.7 on 2018-07-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playname',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='playtext',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
