# Generated by Django 2.0.7 on 2018-07-25 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtext',
            name='play',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plays.PlayName'),
            preserve_default=False,
        ),
    ]
