# Generated by Django 2.0.7 on 2018-07-25 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_auto_20180725_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.PlayText')),
            ],
        ),
    ]
